# Generated by Django 3.1.7 on 2021-03-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0006_auto_20210316_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
