# Generated by Django 3.1.7 on 2021-03-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0020_auto_20210325_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, to='farmer_app.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmer_app.user'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
