# Generated by Django 3.1.7 on 2021-03-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0022_auto_20210329_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, to='farmer_app.OrderItem'),
        ),
    ]
