# Generated by Django 3.1.7 on 2021-03-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0023_auto_20210329_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
