# Generated by Django 3.1.7 on 2021-04-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0027_auto_20210329_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_ordered',
        ),
    ]
