# Generated by Django 3.1.7 on 2021-04-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0030_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('tr', 'Türkçe'), ('es', 'Spanish'), ('en', 'English')], max_length=7, verbose_name='language')),
                ('name_tr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ürün Adı (TR)')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ürün Adı (EN)')),
                ('status', models.BooleanField(default=False, verbose_name='Durumu')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_category', to='farmer_app.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='farmer_app.product'),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('parent', 'language_code')},
        ),
    ]
