# Generated by Django 3.1.7 on 2021-04-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0031_auto_20210406_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_translations', to='farmer_app.product'),
        ),
    ]
