# Generated by Django 3.1.7 on 2021-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0032_auto_20210406_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttranslation',
            old_name='name_tr',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Fiyat'),
        ),
    ]
