# Generated by Django 3.1.7 on 2021-04-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0035_auto_20210407_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
