# Generated by Django 3.1.7 on 2021-04-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0036_auto_20210407_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='category_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='product_status',
        ),
    ]
