# Generated by Django 3.1.7 on 2021-04-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0037_auto_20210408_0851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='booktranslation',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookTranslation',
        ),
    ]
