# Generated by Django 3.1.7 on 2021-04-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0038_auto_20210408_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_ordered',
        ),
    ]
