# Generated by Django 3.1.7 on 2021-04-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0040_orderitem_is_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_status',
            new_name='status',
        ),
    ]
