# Generated by Django 3.1.7 on 2021-04-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0041_auto_20210408_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
