# Generated by Django 3.1.7 on 2021-04-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0042_auto_20210408_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
