# Generated by Django 3.1.7 on 2021-04-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0043_auto_20210408_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('tr', 'Türkçe'), ('es', 'Spanish'), ('en', 'English')], max_length=7, verbose_name='language')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='farmer_app.book')),
            ],
            options={
                'unique_together': {('parent', 'language_code')},
            },
        ),
    ]
