# Generated by Django 3.1.7 on 2021-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0044_book_booktranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_tr', models.CharField(max_length=200, verbose_name='question')),
                ('question_es', models.CharField(max_length=200, verbose_name='question')),
                ('question_en', models.CharField(max_length=200, verbose_name='question')),
                ('answer_tr', models.CharField(max_length=200, verbose_name='answer')),
                ('answer_es', models.CharField(max_length=200, verbose_name='answer')),
                ('answer_en', models.CharField(max_length=200, verbose_name='answer')),
            ],
        ),
    ]
