# Generated by Django 3.1.7 on 2021-04-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0045_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_en',
            field=models.CharField(max_length=200, verbose_name='cevap'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_es',
            field=models.CharField(max_length=200, verbose_name='cevap'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_tr',
            field=models.CharField(max_length=200, verbose_name='cevap'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=200, verbose_name='soru'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_es',
            field=models.CharField(max_length=200, verbose_name='soru'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_tr',
            field=models.CharField(max_length=200, verbose_name='soru'),
        ),
    ]
